### ISSUE TITLE
Add Aternum MiniMap 

### ISSUE THREAD

**Issue by AdrianHDev** [lmachens/aeternum-map#1]
New World doesn't have a minimap built-in to the game.

Proposal: Allow for MiniMap overlay window. 
MiniMap overlay could have features such as:
- transparency 
- round mode
- window decorations.

Monetization: Could use premium subscription for some of the features, but transparency and round mode should probably be included by default. The settings page could also just have an ad similar to the windowed version.

**Comment by lmachens** [comment]
It would be nice to rotate the minimap base on player direction. An option like "North always top" could be useful.
The size should be configurable as well.
