### ISSUE TITLE
Newly created marker appearing in wrong position in certain case

### ISSUE THREAD

**Issue by Sturmfunke** [lmachens/aeternum-map#103]
![image](https://user-images.githubusercontent.com/50137120/138735687-4f754541-3fab-419f-80f5-c007516aafbc.png)

Reproduction:
- Open the menu so that the character symbol moves to the right in the app
- Be aware: The character symbol now is moved to the right side, but not in the middle of the visible map anymore.
- Start the marker creation process
- The newly created marker appears beside the character symbol (distance is half the width of the menu width).

This might be happening because when opening and closing the menu, the character symbol isnt centered on the map anymore (while the marker creation process still puts the marker in the center of the visible map).

Be aware: This also happens when the menu was already open, I moved my character so that the symbol is properly in the middle and then when creating a marker quickly close the menu before the marker gets saved on the map: It gets saved on the wrong position.

Solution: When opening and closing the map, the character symbol should stay centered without having to move the character first to update the position properly.

**Comment by lmachens** [comment]
Could you check if this is still an issue in v1.21.0?
If so, please reopen.

**Comment by Sturmfunke** [comment]
The bug is still reproducable: Stand still, then open the menu (the player icon gets moved to the side) and then create a marker. The marker is set off, because the app creates the marker in the middle of the map (and not where the player icon is), while the player icon is off (half the width of the menu). The player icon gets centered again once I move my character.

Possible solution: When opening or closing the map, move the map focus half the width of the menu to the left / right (depending if menu was open or closed), so the player icon stays centered.

**Comment by Sturmfunke** [comment]
This bug is still happening and I guess it results in wrong positioned markers fairly often.
It happens every when you open the menu and thenn add a marker without moving before it, as the marker still gets created in the center of the window, but not in the center of the map (where the player icon isnt in the middle of the window anymore, because the menu is open). This use case scenario is pretty common.
