### ISSUE TITLE
Repeatable Bug: Filters automatically toggling on/off over and over, using up CPU and requiring a game restart to fix

### ISSUE THREAD

**Issue by RyansGit** [lmachens/aeternum-map#112]
# **Bug**

The bug causes the filters to keep toggling on and off over and over again endlessly using up loads of CPU as it's redrawing icons over and over on the map.

The only way to fix it is to restart your game.

# **How to reproduce?**

Simply click on two filters in quick succession (the slower your device the easier it is to do this). I ran into it by clicking on "Mining" and "Essences" which are pretty heavy in how many filters are being enabled/disabled.

Once you click both of them in quick succession, wait 30 seconds and you should see one of them automatically enabling/disabling over and over without you touching anything.

**Comment by lmachens** [comment]
Thanks! Could you check if you still face this issue in v1.21.0?
If this is still an issue, feel free to reopen.
