### ISSUE TITLE
Marker position

### ISSUE THREAD

**Issue by VatriXxX** [lmachens/aeternum-map#125]
Hello,
is it possible to remove the close position to other markers?
I would add every plant or ore in 5 meters radius

Greetings

**Comment by lmachens** [comment]
Hi,
I reduce the minimal distance in #128 by 50%. I can reduce it a bit more, but I don't think it makes sense to remove the check completely. What do you think?

**Comment by VatriXxX** [comment]
Yeah it's better but, actually is the same thing often at herbs and hemps.
It's the same issue, "A similiar marker is too close".
