### ISSUE TITLE
[ Enhancement ] Resize new route screen.

### ISSUE THREAD

**Issue by yLordMagnus** [lmachens/aeternum-map#135]
### Suggestion:

* Be able to resize new route screen.

I see myself almost entering my monitor when creating routes because the screen is so small, it would be really nice to be able to resize it or make it fullscreen.

**Comment by rubybrowncoat** [comment]
Being able to move it around would allow us to have a detailed view when making a route and a larger view on the map itself to orient ourselves while planning the route.
