### ISSUE TITLE
Cyan Prismabloom

### ISSUE THREAD

**Issue by Turom421** [lmachens/aeternum-map#138]
Please add Cyan Prismabloom.  I found a few nodes yesterday in Reekwater.  If you look at your index of items, someone put a miscellaneous item at the southern end of Reekwater -- that's Cyan.  I didn't add the other one I found because I didn't want something to be mislabeled.

**Comment by Triadian** [comment]
You Have :-

-Black Prismabloom
-Blue Prismabloom
-Brown Prismabloom
-Green Prismabloom
-Orange Prismabloom
-Red Prismabloom
-White Prismabloom
-Yellow Prismabloom

You Shouldn't Have :-
- Purple Prismabloom

You Need :-
Cyan Prismabloom
Magenta Prismabloom - some markers are named purple
Turquoise Prismabloom
Violet Prismabloom - some markers are named purple

if you can DB pull all co-ordinates of Purple prismabloom those above 4000 Y are Violet those below 4000 Y are Magenta
