### ISSUE TITLE
Add Outpost Rush Map

### ISSUE THREAD

**Issue by DerekZil** [lmachens/aeternum-map#143]
Add the **Outpost Rush** map.
This will help to find resources more efficiently.

If Trees/Ores/Skinning will be added as well that would be awesome.

-DAZ

**Comment by DerekZil** [comment]
Two more things if you can add below:

1.) Add Outpost Rush to the NPC category. (With the symbol.)
2.) Add Dungeon maps too.

**Comment by Sturmfunke** [comment]
> 1.) Add Outpost Rush to the NPC category. (With the symbol.) 
I dont know if I understand you corectly. Its the same NPC as the faction quests. I wouldnt put two different markers at the same location. Also, its common knowledge that you can join Outpost Rush via that NPC. But maybe I misunderstood you.

**Comment by lmachens** [comment]
Already added
