### ISSUE TITLE
Route Creating / Editing & Route Display Improvements

### ISSUE THREAD

**Issue by RyansGit** [lmachens/aeternum-map#148]
Hi,

I'm constantly tweaking my routes and it's a pain to re-create routes from scratch every time...

# Route Editing

1. If you click on a line and start to drag that line, this line should change to a dot (point) which you can drag and drop onto a new area to add a point to your route.
2. You should be able to delete existing points on the map by right clicking and deleting or some hotkey like pressing delete when hovering over it.
3. You should be able to click "Edit Route" which will start re-editing the route allowing you to extend onto the end of the route.

# Route Creation

1. Do not allow you to accidently click outside of the popover, if you do it should not close the route.
2. If you accidently right click you should be able to click "Edit" and start adding more points to the route.
3. If you accidently left click on one of your points and thus end the route, you should be able to click edit to start adding more points to the route.
4. If you spam revert points on the route, it should not zoom in.

# Route Display

1. The start of the route should have a different color dot/point because some routes require you to go a specific way because of the terrain making some mountains impassable if you start from the wrong end of the route.
2. If you follow near a route it should start changing color to show that you've done that part of the route. After you leave the route (Travel x distance away from the point you at) then it would reset to the original color.

**Comment by lmachens** [comment]
Thanks for your requests. #150 solves some of your issues. Please update your description (remove solved issues).

**Comment by lmachens** [comment]
More issues of this requests will be fixed in #163.
