### ISSUE TITLE
Add a "Save/Load Preset" function beside "Show/Hide All" markers

### ISSUE THREAD

**Issue by Sturmfunke** [lmachens/aeternum-map#152]
As showing all markers on the map includes too much irrelevant information for me, I have my own standard "marker setup" where I have certain markers always hidden.

After changing my marker setup for a specific situation (e.g. a farming run or searching for a certain marker type on the map), I always have to click "show all" again followed by hiding all markers I generally dont want to see. It happens quite a lot in my gaming sessions.

I would like to have a quick "save preset" and "load preset" function for my own standard marker setup.
(In the future, this can be developed even further to give the user the opportunity to save multiple marker setups and also give these setups names.)

**Comment by Szyler** [comment]
I have the same issue, this feature would be great.

**Comment by Acanis87** [comment]
That would be really nice! ^^
