### ISSUE TITLE
Minimap options (F5) Only visible while minimap is rotating

### ISSUE THREAD

**Issue by darkscion0** [lmachens/aeternum-map#153]
Got the new version and wanted to turn off the map rotation. When I hit F5 the options wouldn't show, but if I moved in a way that the minimap rotated, they options appeared and then disappeared again when the rotation was done.

**Comment by lmachens** [comment]
Thank you. Could you share a clip or screenshots of this behavior?

**Comment by darkscion0** [comment]
Unfortunately I cannot. I was able to spin the minimap long enough to uncheck minimap rotation and now I'm unable to get the options (F5) to appear at all.

**Comment by darkscion0** [comment]
If I hit F6 F6 F5 in quick succession to close and open the minimap, I can get the options to stay on screen for about half a second.

**Comment by lmachens** [comment]
Already fixed
