### ISSUE TITLE
Large Jump in CPU Usage after 1.23.4 Update

### ISSUE THREAD

**Issue by darkscion0** [lmachens/aeternum-map#154]
Running an Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz and now seeing Overwolf CPU usage of up to 12.9% while moving in-game.

**Comment by lmachens** [comment]
The minimap rotation will increase your CPU usage. Please make sure to deactivate it for now or reduce the number of markers visible (by hiding markers or changing zoom level).

Can you approve that it's related to the rotation?

**Comment by darkscion0** [comment]
I've already disabled minimap rotation and the CPU usage remains around 12% while moving. I'm wondering if it's due to the state my minimap is in as I submitted the other bug this morning for minimap options now showing unless the minimap was rotating and now I can't get the options back at all.

**Comment by lmachens** [comment]
I think it's not an issue anymore. CPU usage is way better than before :)
