### ISSUE TITLE
Routes should not require to include markers / Can't save route

### ISSUE THREAD

**Issue by Sturmfunke** [lmachens/aeternum-map#158]
I am now 2 hours in, still trying to create a route. Now that I finished it, I wanted to save it, but it seems to be not possible.
My route does not include any markers, as it is a PvP faction quest.
I don't know if this is a bug that I am not able save it or that if  a route requires markers to be selected in order to save it.

![image](https://user-images.githubusercontent.com/50137120/141303786-00f73411-d00c-4535-a4b5-8d5cf9aa8312.png)

**Comment by lmachens** [comment]
It's not possible to save a route without markers. I didn't know that it's a use case.
I will make it possible 👍
