### ISSUE TITLE
Ability to resize markers

### ISSUE THREAD

**Issue by wesh92** [lmachens/aeternum-map#16]
Hello Leon! Unfortunately, JS/TS is not my language or I'd pitch in on this but is there a way we could get a sizing gauge on the markers. Currently, the markers are a bit small in their circles but I understand that some may not like bigger icons. While I believe a slider might be the best option here, any kind of resizing option for the icons would be nice!

Thanks for all your work on this and keep it up!

**Comment by MidasOfSweden** [comment]
I would like to be able to resize the icons but make them smaller actually, so a slider to change the size would be awesome :) And maybe a box to make the icons smaller as you zoom out the map to keep it consistent scale
