### ISSUE TITLE
Redesign of the marker window

### ISSUE THREAD

**Issue by Sturmfunke** [lmachens/aeternum-map#168]
I have a proposal for a better arrangement of elements in the marker window.

At the moment, the description / custom title of Miscellaneous markers is a bit "hidden" between other information.
Below is an example. The description "turkey nest" does not stand out. I would like to have this information at the top in bigger font size. In case the marker is a Boss, the name and level would be at the top.

Marker window how it is currently:

![Unbenannt1](https://user-images.githubusercontent.com/50137120/141697125-5a64116e-39e5-4ba9-aeb3-5fe380a4c430.png)

Marker window concept:

![Unbenannt2](https://user-images.githubusercontent.com/50137120/141697144-a913feff-02c2-461f-85cc-e83add5a8f99.png)

**Comment by Triadian** [comment]
what about markers without descriptions ? 
![image](https://user-images.githubusercontent.com/18445590/142365811-5c154266-357f-406e-935b-4a4afb82b49e.png)

if the miscellenaous markers were fixed like turkey nests etc - would this still be needed ?

**Comment by Sturmfunke** [comment]
> what about markers without descriptions ? 

If the marker has no description, the description area would be hidden, with only one horizontal line, just like it is right now.

> if the miscellenaous markers were fixed like turkey nests etc - would this still be needed ?

Yes, there are still other misc markers and markers with desciptions / names like Elites and Bosses.

**Comment by lmachens** [comment]
Node details looks different now
