### ISSUE TITLE
Add button to copy marker coordinates to the clipboard

### ISSUE THREAD

**Issue by Sturmfunke** [lmachens/aeternum-map#179]
- Add a little clickable symbol to the right of the coordinates.
- Clicking it will copy the coordinates to the clipboard, so I can use Ctrl+V and share the coordinates somewhere else.

It makes sharing coordinates / markers with friends etc. easier.

![image](https://user-images.githubusercontent.com/50137120/142421790-eb2262a0-328e-4a28-b873-93cfa2339c9e.png)

**Comment by dillontherrien** [comment]
#195 

Created pull request to add this feature
