### ISSUE TITLE
Aeternum-Map not relocating back from OutPost Rush

### ISSUE THREAD

**Issue by YellowFlashx** [lmachens/aeternum-map#185]
about 3 nights ago I went into a outpost rush game, and as it was just about to start I launched the program soI can have the minimap, hoping that it will have the OPR map but it didn't all it showed was a grey radar. 

I waited until the OPR finished to see if it will relocate me back to the location I was last, and see if the minimap fixes itself but it didn't.
it still registered me still in the OutPost Rush Map for some reason.

- I tried teleporting to a town, - didn't work
- re-opened closed the app and the game
- my final solution is that I just uninstalled it,  if I can replicate it and record it, I'll give the evidence over. Could be a 1 time thing

**Comment by lmachens** [comment]
did it happen again?

**Comment by lmachens** [comment]
I guess this was a temporary issue. If it still happens, please reopen.
