### ISSUE TITLE
Alchemy Elite and Provisions Elite markers listed as "0" in the marker menu

### ISSUE THREAD

**Issue by Sturmfunke** [lmachens/aeternum-map#188]
Alchemy Elite and Provisions Elite dont have any markers.
It is unclear if the markers are not showing at all if all chest types are activated, or if these two specific times are falsely integrated into other types.

![image](https://user-images.githubusercontent.com/50137120/142762571-a4572145-0c9c-4542-a07f-773c066db4c4.png)

**Comment by Triadian** [comment]
looking at other map sites they dont exist 
![image](https://user-images.githubusercontent.com/18445590/142901462-22a828e6-4881-4de4-90f1-b4b5b0218a8f.png)

**Comment by Sturmfunke** [comment]
Depending on how Aeternum Map does even differenciate between the chests. Becasuse T4 and T5 doesnt exist there (Tiers are mostly unrelated to the type of chest (Cache, Crate, Stockpile).

Also, as this change isnt mentioned anywhere, and nobody said he did it intentionally, I have to assume that it's a bug or unintended outcome how it is right now.

I agree that we need better naming / categories for the chests, that give more consistency.
Your renaming suggestions in Discord would fit well. I would not integrate the Tiers in the marker menu, but seperate the big chests (Supplies Stockpile and Ancient Chests), that are in Elite areas (all the chests on nw-map labeled as T4 and T5).

I suggest to change the chest category to look like that:

Ancient Elite | Supplies Elite [Both types are what we have right now as Elite listed, no changes here]
Alchemy Stockpile |  Anchient Chest | Provisions Stockpile | Supply Stockpile
Alchemy Crate | Ancient Coffer | Provisions Crate | Supply Crate
Ancient Urn | Provisions Cache | Supply Cache [A third Alchemy chest type doesnt exist]

The big question is: Where did Aeternum Map mix two chest types together? Looking at the chest category right now, we have Elite, Large and Commong. Elite stays Elite, but what is Large and what is Common? I guess Large is Stockpile and Chest, but that means that Common Crate and Coffer, but also Urn and Cache. If there is information in the database to separate it, that would be great.

**Comment by Triadian** [comment]
yeah i think we need a new icon for Large

**Comment by Triadian** [comment]
ill work on it tonight see what i can do
