### ISSUE TITLE
Player updates are not send from app to browser via websocket if group tokens do not match

### ISSUE THREAD

**Issue by sbrinager** [lmachens/aeternum-map#190]
After setting up the new add-on/website combination, my browser was not receiving updates when I moved in-game. Afer inspecting the websocket messages, I noticed no updates were being sent. I had generated codes for both player and group in the browser first, then pasted the player token into the addon, but didn't bother with the group token since I primarily care about my location. Until I made sure both matched, no updates would be sent. It seems the channel is tied to the pair of keys. For performance sake, it might be more CPU efficient to maintain 2 sockets, 1 for player and 1 for group, rather than sending everything across a single socket. Personally, I would like to be to use a company group token, but turn it off at will so I could reduce clutter on my map.

**Comment by Triadian** [comment]
use the same token just add a 1 on it ? it become a solo token

**Comment by sbrinager** [comment]
I guess I should have created 2 issues. The web socket room being identified by a combination of BOTH tokens is what I reported, which isn't a big deal, but in realizing that was the issue I was seeing, it sparked the idea that having the socket logic use separate sockets for player vs group data or 2 distinct rooms with the option to turn off group data (if my company uses a common group key, there are lots of time that I don't want to have that amount of data streaming to my browser constantly)

**Comment by lmachens** [comment]
I guess this is not an issue anymore because we are using a single token.
If not, please reopen.
