### ISSUE TITLE
Allow user to display/capture a small QR code to link the overlay and web app.

### ISSUE THREAD

**Issue by tomgrice** [lmachens/aeternum-map#193]
I've been using an android tablet as a side-monitor with the web app running on it as a minimap and it works great.
I thought it could be handy to be able to sync them by capturing a QR code with the device camera rather than manually typing in codes or logging another device into Steam.

Probably not an update high in demand, but might take a stab at it myself when I get chance to get my head around the source, if a dev/contributer doesn't.

**Comment by lmachens** [comment]
I don't think this is required anymore, because the code is automatically shared if you log in with Steam.
