### ISSUE TITLE
not properly working Vivaldi browser

### ISSUE THREAD

**Issue by Ragmir** [lmachens/aeternum-map#196]
it's not a big deal but you can't left mouse click in a node in Vivaldi browser, but you can drag the map around, weird stuff

**Comment by lmachens** [comment]
Vivaldi works for me:

![image](https://user-images.githubusercontent.com/10058950/143778790-7cf7b6c7-e611-48bd-bd41-c7bffc08ac79.png)

Could you give me more details and share browser console logs (`CTRL+SHIFT+I`) and reopen, if this is still an issue?
