### ISSUE TITLE
[Suggestion] Show tracked friends in different colors like in the game it self.

### ISSUE THREAD

**Issue by Cabola** [lmachens/aeternum-map#210]
Right now playing with tracked friends in a group shows all as white, and can become confusing. If each tracked player had a different color, like they already do in the group option in game, then it'd be less confusing. This could be done with something like [https://github.com/zenozeng/color-hash](https://github.com/zenozeng/color-hash) and using the steam id as the identifyer for who's who.

Originally suggested on discord by mightyjosHi#1175 and the color-hash was suggested by Virtualbs#0290

**Comment by Triadian** [comment]
i personally would prefer a color option in settings either with a hex text entry or a colorbox popup

**Comment by Cabola** [comment]
> i personally would prefer a color option in settings either with a hex text entry or a colorbox popup
I don't really care how the different colors are added, but yes, a default of like 10 colors in a settings page could be useful.

**Comment by Timitrion** [comment]
I would really appreciate that
