### ISSUE TITLE
Add Expedition Maps

### ISSUE THREAD

**Issue by Acanis87** [lmachens/aeternum-map#216]
Hey, like you did with Outpost (https://github.com/lmachens/aeternum-map/issues/143), adding a map for the expeditions would be really cool.
Just to finding ressources and chests easier and to have something "valid" on the map-screen, while you are running expeditions ^^

**Comment by josdemmers** [comment]
This please. Would be really helpful to have a useful map while in a dungeon.

- Amrine Excavation
- Starstone Barrows
- The Depths
- Dynasty Shipyard
- Garden of Genesis

**Comment by lmachens** [comment]
I already found the map tiles for the expeditions, but I need to know if NW is using a new map or it's part of Aeternum.
Can someone check which coordinates are detected if you are in one of these dungeons?
The position detected by Aeternum Map and the position in-game (FPS activated) are useful for me.

**Comment by josdemmers** [comment]
Just used up all my tuning orbs today, will try to visit some of them the following days. But I can only go to the first three yet, need to level up a bit first for the others.

**Comment by josdemmers** [comment]
Coordinates for The Depths

![depths_begin](https://user-images.githubusercontent.com/8627157/147793775-8e16e755-43cc-4b63-856b-c86f9e7e1972.png)
![depths_end](https://user-images.githubusercontent.com/8627157/147793777-57d8a870-6cac-42a7-a3fa-477d58cd611a.png)

**Comment by lmachens** [comment]
I have the feeling, that every expedition is near these coordinates. Can someone try out a different one?

And please share your share token with me if you are doing a expedition.

**Comment by josdemmers** [comment]
Completed this one before you message. But yes, looks like they are very near each other.
This one is for Amrine.

![amrine_begin](https://user-images.githubusercontent.com/8627157/147819849-9fcc5f82-a40c-4859-abf4-972eff8ed098.png)
![amire_end](https://user-images.githubusercontent.com/8627157/147819851-32e7ff79-5275-4da3-9195-42c034ee3f3c.png)
![amire_end2](https://user-images.githubusercontent.com/8627157/147819854-d88840f7-724b-4d05-9f20-d70d0c92cdde.png)

**Comment by lmachens** [comment]
There is a flag in the Overwolf Api which tells me the current map. Maybe this is changed if you are on an expedition. This would be awesome :).
Can you check this next time you play?

Open live share details (which includes the current map). Replace the Token with your share token and share map result with me. In best case, the map is different if you are on an expedition. We need to find out the different names. 

EUROPE:  https://live1.aeternum-map.gg/api/live/TOKEN

US:

https://live2.aeternum-map.gg/api/live/TOKEN

**Comment by lmachens** [comment]
Starstone Barrows: `NW_Dungeon_Everfall_00`
Amrine: `NW_Dungeon_Windsward_00`

**Comment by Acanis87** [comment]
Maybe the rest follows this pattern?^^
The Depths: NW_Dungeon_RestlessShore_00
Dynasty Shipyard: NW_Dungeon_EbonscaleReach_00
Garden of Genesis: NW_Dungeon_Edengrove_00
Lazarus Instrumentality: NW_Dungeon_Reekwater_00

**Comment by lmachens** [comment]
Maybe :), I can prepare it with your list and "fix" it afterwards if some of these are not correct. Thx :)

**Comment by Acanis87** [comment]
Nice ^^ Its easier to give feedback after this. I didnt understand how to provide the current map info from the Overwolf API, but if there is a version that should show the map, its easy to see, if its working :D

**Comment by josdemmers** [comment]
Tested Depths but name was different than we assumed, correct name for Depths is:
NW_Dungeon_RestlessShores_01

**Comment by lmachens** [comment]
Thx, this is useful. This will be the next task I like to work on. Hopefully, I can finish it on Friday.

**Comment by josdemmers** [comment]
Dynasty shipyard is already working, it's located on the normal map.
"map":"NewWorld_VitaeEterna"

**Comment by lmachens** [comment]
The map tiles are in these folders:

```
nw_dungeon_edengrove_00
nw_dungeon_everfall_00
nw_dungeon_reekwater_00
nw_dungeon_restlessshores_01
nw_dungeon_windsward_00
```

I guess, these are the maps we are looking for :)

**Comment by lmachens** [comment]
This will take more time to implement.
I have to add new maps and add properties to markers and routes, for which map they belong to.
The position `[x,y]` is not unique, because it depends on the current map. The outpost is part of the main map, but not the expeditions.

In addition, there must be a smooth way to select the different maps.

The good news is, that it's possible, and it just takes a bit longer than expected. 

![image](https://user-images.githubusercontent.com/10058950/148551805-ed160c6d-4d68-4008-ada6-c816de4e5240.png)
