### ISSUE TITLE
Add quest pins viewable by only myself and others using my token

### ISSUE THREAD

**Issue by neotrin2021** [lmachens/aeternum-map#221]
Couple of things, Could we get the ability to add our own pins to the map so we can open our in-game map, find our quest markers and put drop pins on your map so we can see where we have to go for quests?  BONUS: if you can make 2 sets of pins Diamond for normal quests and Circle for Covenant quests.  Also make the pins only viewable client side and not for the rest of the world to see.  Or maybe those types of pins only viewable to myself and those using my link code.  Of course that means others can add pins as well.  But their pins would show up as a different color than mine (Like the game does it when we are in a group and drop a pin on the map.)  Of course give us the ability to remove our own pins so we don't clutter up our map.  (Side Note: for you it would be great the more people that use this function: the faster you could get quest locations for use in future projects)

**Comment by Sturmfunke** [comment]
Relevant: https://github.com/lmachens/aeternum-map/issues/6 [Add custom markers]
