### ISSUE TITLE
[Suggestion] Possibility to delete any part of a route instead of only the last part

### ISSUE THREAD

**Issue by josdemmers** [lmachens/aeternum-map#257]
Currently you can only choose "Remove last Vertex" for deleting the last part of your route.
Would be great if it was possible to delete any part of your route.

![image](https://user-images.githubusercontent.com/8627157/150210569-b64acca5-9826-44e3-86ad-dc8b49476563.png)

For example if you delete node 2 then the route will automatically connect node 1 to node 3 and node 2 will be removed from the route.

**Comment by lmachens** [comment]
See note:
![image](https://user-images.githubusercontent.com/10058950/150211330-df6f201c-185f-4204-8704-ce3137269742.png)

You can right-click on a node to remove it. 

Feel free to reopen, if this doesn't solve your issue.

**Comment by josdemmers** [comment]
That is great, missed that completely. Issue solved.
