### ISSUE TITLE
Respawn timers

### ISSUE THREAD

**Issue by lmachens** [lmachens/aeternum-map#263]
With the latest release (https://github.com/lmachens/aeternum-map/releases/tag/v1.20.0-web), it's possible to add respawn timers to nodes nearby.
The timers are not correct, and we need your help to update this list:
https://github.com/lmachens/aeternum-map/blob/main/src/app/components/WorldMap/actions.ts#L73-L154

Please comment here if you find invalid timers.

Note that I selected a median for veins like `iron`, because the timers are different for large/medium and small nodes.

After we solve this issue, we could think about implementing #147.

**Comment by Cabola** [comment]
From https://newworld.wiki.fextralife.com/

**Seeping Stone (Oil)**
Small - 503 - 720 Seconds
Medium - 630 - 900 Seconds
Large - 714 - 1020 Seconds

**Iron Vein**
Small - 503 - 720 Seconds
Medium - 630 - 900 Seconds
Large - 714 - 1020 Seconds

**Starmetal Vein**
Small - 756 - 1080 Seconds
Medium - 944 - 1350 Seconds
Large - 1071 - 1530 Seconds

**Comment by ryantaplin** [comment]
Fishing Hotspots

Based on https://nwdb.info/
| Hotspot  | Time Min | Time Max | 
|-------------|----------|----------|
| Broad        | 1200      | 1800      |
| Rare          | 1800      | 2700      |
| Secret       | 2700      | 5400      |

Some prelim investigations of rare hotspot ingame (WIP):
![image](https://user-images.githubusercontent.com/11903234/150700888-0551feea-dcba-4fbf-8f67-fe261daa77d7.png)

**Comment by lmachens** [comment]
Thank you, 
I think this is more difficult to solve because of the different sizes and ranges.
I will use the max medium time for the items of @Cabola list.
And the max time for the hotspots.
