### ISSUE TITLE
Separate sizes of veins like iron, silver, gold

### ISSUE THREAD

**Issue by lmachens** [lmachens/aeternum-map#279]
Right now, we don't track the size of minable nodes, which makes it impossible to use correct respawn intervals.
We like to add the different sizes to these nodes.

Which nodes are effected and do they all have three different sizes (Small, Medium and Large)?

After this change, we can adjust the respawn timers.
Iron Example:
[8m 24s, 12m], [10m 30s - 15m] and [11m 54s - 17m]
Source:
https://nwdb.info/db/gatherable/oreveinsmall https://nwdb.info/db/gatherable/oreveinmedium https://nwdb.info/db/gatherable/oreveinlarge

**Comment by lmachens** [comment]
For farming:
Hemp, Herb, Silkweed, Wirefiber

Logging:
Ironwood tree, Wyrdwood tree

Mining:
Everything. 
(Except the crystal. Crystal can be removed. Verified all spots and it does not exists anywhere)

**Comment by ryanaslett** [comment]
Hi, the sizes for woods are not correct. There are five sizes: XS, S, M, L, XL

**Comment by lmachens** [comment]
> Hi, the sizes for woods are not correct. There are five sizes: XS, S, M, L, XL

Thx, I can't find `XL`. Are you sure, that this exists?
