### ISSUE TITLE
Add Marker for Rafflebones Locations

### ISSUE THREAD

**Issue by Malek-Zandor** [lmachens/aeternum-map#281]
As title says please add a separate marker for possible spawn location of Rafflebones

**Comment by lmachens** [comment]
Which category and icon would be suitable?

**Comment by josdemmers** [comment]
In the Enemies category I think. As icon same as boss/elite boss but then with a green/dark green color?
Because Rafflebones is a loot goblin green seems to be a good color.

**Comment by josdemmers** [comment]
Something like this?
![icon_dungeon_map_boss_green](https://user-images.githubusercontent.com/8627157/161399094-eccb010d-bebc-4b63-805a-c668213995b8.png)

**Comment by Malek-Zandor** [comment]
I like both
