### ISSUE TITLE
Node groups with subdivisions cannot be toggled on via their header

### ISSUE THREAD

**Issue by lhargraves95** [lmachens/aeternum-map#287]
When e.g. chest markers are visible on map, clicking the Chests header will hide all chest markers.
- This is good.

When no chest marker are selected, clicking on the header does not make all chest markers visible again.
- User has to click on each chest type to make them visible again.

Same applies to node groups that include nodes with subdivisions like size or tier.

In a common use case where a user hides a large number of groups of nodes then adds back a small handful of nodes, while planning a route or just looking for a particular resource in a clump, resetting the map to show all the nodes previously selected is time consuming.

**Comment by ryantaplin** [comment]
I tried a few heading's and all exhibit the same behaviour (hide/unhide all).

Either this has been fixed already or maybe there's a specific header that is having problems? 

If it's still a problem can you elaborate a bit more.

**Comment by lmachens** [comment]
It should be fixed
