### ISSUE TITLE
Screens Flickering Black

### ISSUE THREAD

**Issue by LactaCorpora** [lmachens/aeternum-map#302]
So after downloading everything, and having a fresh install I started using the Aeternum-map on my second monitor. After having it open I started having issues where my screens were flickering black, badly. Today I finally solved the puzzle, and realized that it is only when having that browser open. The worst spots it causes flickering is while in Edengrove.

I am running a Radeon 5700 XT GPU, AMD Ryzen 3700 GPU, and 2 monitors. One is a acer 165hz, 0.5ms refresh with amd freesync. The other is just a shitty little Onn monitor from walmart. I've had 0 issues up until I started using the Aeternum-map.

**Comment by lmachens** [comment]
Hi, do you have the same issue with other Overwolf apps?
I don't think it's related to Aeternum Map, because it's technically only a website.
I would check if it's related to HDR, if you have it activated.

**Comment by LactaCorpora** [comment]
It only happens when I was using the Aternum-map. I changed a setting in chrome, and I redownloaded the map. This is the only game I use overwolf for. I'll let you know if it corrects the issue.

After I made this post I tried to a few more times and it did the same thing, so I uninstalled overwolf and the map. Didn't have any issues for a week. So we'll see this time.

**Comment by lmachens** [comment]
Very weird, but it's good that it works now.
Still, I don't think it's related to Aeternum Map. Maybe it's an issue in Overwolf, in this case, better ask the Overwolf support if it happens again.

Thx for keeping me up-to-date.
