### ISSUE TITLE
[Suggestion] Outline Silk Icon 

### ISSUE THREAD

**Issue by zachs1** [lmachens/aeternum-map#325]
Difficult to see in map, bright outline would make huge difference

**Comment by lmachens** [comment]
You can activate marker background in the settings. Does this solves your issue too?

**Comment by zachs1** [comment]
Yes! Thank you

**Comment by zachs1** [comment]
It would be nice to not need this as it clutters the screen when tracking many resources, but it does solve my issue.

**Comment by lmachens** [comment]
Ok thx, I can update the icon.
Are there other icons too which are not easy to see?
