### ISSUE TITLE
Shared Live Status Issue

### ISSUE THREAD

**Issue by Fongshu** [lmachens/aeternum-map#347]
Since the update with Brimstonesands I have not been able to have my shared live status work.  Is there an update that I need to upload for it to go back to working again.  Before that update I had no issues using the app.

Thanks
Fong

**Comment by lmachens** [comment]
Hi, please join the Discord and follow #nw_updates to keep up to date about this issue.
Overwolf has some issues recently with the position detection for some users. They are working on a fix.

In the meantime, please activate "Show FPS" ingame to display the coordinates. Aeternum Map will fallback to screen capturing via OCR.

If this doesn't work, it can have multiple reasons and I need more information.

**Comment by Fongshu** [comment]
Ok I will log on early in the morning, I did see the notation on "Show FPS" but have not seen any results from that I even re-downloaded the APP to see if that would help but still nothing.  Will get on the discord and see what we can do. 

Thanks!

**Comment by lmachens** [comment]
There is no easy on your side, because it's an issue in the Overwolf API.
It only happens for some users, so I think it's related to your hardware, drivers or libraries.

**Comment by PhantasmalSexGod** [comment]
Having similar issues. Just subbing to this thread for any updates  / API fixes.

**Comment by lmachens** [comment]
> Having similar issues. Just subbing to this thread for any updates  / API fixes.

Hi,
There is a good workaround.
Please activate "Show FPS" in game and set brightness and Contrast to `5`.
Aeternum Map will fallback to screen capturing as long as this issue is not completely fixed on Overwolf side.

Does it work for you?

**Comment by lmachens** [comment]
And make sure to join my Discord for updates.

**Comment by alanowns** [comment]
> > Having similar issues. Just subbing to this thread for any updates  / API fixes.
> 
> Hi, There is a good workaround. Please activate "Show FPS" in game and set brightness and Contrast to `5`. Aeternum Map will fallback to screen capturing as long as this issue is not completely fixed on Overwolf side.
> 
> Does it work for you?

I did have my  brightness set to 7 so I set it back to 5. It didn't help. I'll join your discord.
