### ISSUE TITLE
Game cannot start with this

### ISSUE THREAD

**Issue by vekexasia** [lmachens/aeternum-map#355]
Hello I'm on W11 can't start the game unfortunately. it freezes in the amazon logo. I tried waiting 5 mins.

**Comment by vekexasia** [comment]
hey @lmachens can you link the ds for me plz?

**Comment by vekexasia** [comment]
PS: I don't have neither overlays

**Comment by lmachens** [comment]
> hey @lmachens can you link the ds for me plz?

https://discord.gg/NTZu8Px

**Comment by Cinerar** [comment]
Same issue on w11 with no other overlays

**Comment by lmachens** [comment]
> Same issue on w11 with no other overlays

Hi, please join the Discord for more support. 

If the game freezes, the Screenshot for the OCR hangs. Please verify again that no other tools like Discord Overlay, GeForce experience or similar is running.

Usually, the game unfreeze after 5-10min, if you don't find a solution.
