### ISSUE TITLE
Presets not saving

### ISSUE THREAD

**Issue by joelm3103** [lmachens/aeternum-map#430]
When I try saving a preset, it saves the name but the preset is empty (all nodes unselected).

Tried clearing cache and also cleared all data locally for site (using Chrome Version 108.0.5359.125 and also tested on MS Edge).

**Comment by lmachens** [comment]
Thx, will be fixed in upcoming release.
You can join the [Discord](https://discord.com/invite/NTZu8Px) for the release notes and notification about new releases.
