### ISSUE TITLE
Difficulty displaying https://aeternum-map.gg/minimap.html in Skeleton

### ISSUE THREAD

**Issue by dpcollier128** [lmachens/aeternum-map#431]
I'll get to the point here. https://aeternum-map.gg/minimap.html refuses to show up within Skeleton now. I think this is an Aeternum map issue, not a Skeleton issue, because Skeleton hasn't been updated in several months, but the Aeternum map site has been rather frequently updated over the past few days. One change to the site could have broken this functionality, but I don't know enough to be sure. What's odd is that navigating to the minimap site in my usual browser shows the map without issues. Only Skeleton seems to be showing nothing when I go there.

I usually enable the minimap to display in the upper left of my screen, always on top with click-through and transparency. I also set the border size to none, so it appears square. Still, ever since this afternoon, when I reloaded that Skeleton window, it hasn't worked at all. It's completely invisible, and the task view only shows an empty app window when I alt-tab through my open apps. I tried mousing over the area where it should be to somehow cause it to fade back into view. I tried pressing my display/hide hotkey in Skeleton. I tried rebooting my system. I tried toggling the minimap window on and off several times, along with its companion window with the full map and settings. Nothing has worked to make the minimap site as visible as it once was.

Is this it? Did AGS call for this function to be shut down from the site-side app?

**Comment by lmachens** [comment]
Hi, please reset Skeleton and try again. By the way, make sure to join the [Discord](https://discord.com/invite/NTZu8Px) for faster support :).

Skeleton related data is stored in:
%APPDATA%\skeleton 

1) Close skeleton app
2) Open %APPDATA% in your explorer 
3) Remove skeleton folder
4) Open Skeleton app

**Comment by dpcollier128** [comment]
Oh, sorry. I didn't realize that you were the same developer for both apps. According to your instructions, I fixed this. I guess every browser needs to reset once in awhile.
