### ISSUE TITLE
route error

### ISSUE THREAD

**Issue by krystias80** [lmachens/aeternum-map#433]
I am having an issue where i cant add or delete routes. It keeps telling me something went wrong. 
![Capture](https://user-images.githubusercontent.com/120116000/208922216-f7792637-207d-4c43-a142-0f57e10a0cf0.PNG)

**Comment by lmachens** [comment]
Hi, please reset your browser cache and try again. There was a temporary issue, which is still in cache. 
By the way, make sure to join the [Discord](https://discord.com/invite/NTZu8Px) for faster support :).
Feel free to reopen this or ask in Discord if this is not fixed.
