### ISSUE TITLE
The close button on the top right on the map is misleading, it should hide, not close the whole program.

### ISSUE THREAD

**Issue by nixxou** [lmachens/aeternum-map#50]
There is a cross to close the map on the top right. But if you click that actually unload the program. I don't count how many time i unloaded the program when I just want to hide like f4
For me, the close button is misleading and an UI error, it should close (aka hide) the map, not the whole program (minimap and such) and an other button like exit program should be somewhere else in the menu.

When you walk outside with your map out that take half of your screen and you want to close it and you see the close button, i often just click, just by pure reflex. And ... oh shit, the whole program is unloaded.

**Comment by lmachens** [comment]
I don't think this is an issue anymore because the map is not part of the Overwolf app anymore. If not, please reopen.
