### ISSUE TITLE
Show region borders on map/minimap

### ISSUE THREAD

**Issue by darkscion0** [lmachens/aeternum-map#54]
Like this:

![image](https://user-images.githubusercontent.com/8334966/137569993-b33b4e5b-c405-4b7e-97f2-854d3454c0c1.png)

**Comment by timothyfox443** [comment]
I would also like to request this but be able to have it toggle on and off.  This is rather useful to those of us that would like to know when we cross into a territory with the dreaded insta-gib skulls.  If you know what I'm referring to, you have my pity.
