### ISSUE TITLE
Feature request: Cooldown for chest(elite)

### ISSUE THREAD

**Issue by NorbertasL** [lmachens/aeternum-map#55]
Could you add some form of timer for chests? For example elite chest have 24h cd before you can loot them again and they seem to be the top way to get your GS up 😄

**Comment by razfriman** [comment]
this data can be found on NWDB. Includes respawn times for pretty much every item in the game 

https://nwdb.info

**Comment by nixxou** [comment]
Yup, but how can you know if your character has open the chest ? Maybe something like click on the icon in the minimap ?

**Comment by NorbertasL** [comment]
manual key bind would be ok as a start and in the future maybe catch the looting circle?(I know that's not easy) 
So manual would be: I press F5 and the closes chest to me goes on CD.
