### ISSUE TITLE
Add a comment log for moderators, showing recent comments

### ISSUE THREAD

**Issue by Sturmfunke** [lmachens/aeternum-map#64]
Having a log of all comments, ordered by date, would make moderating much easier.
Comments could be deleted directly via the log.
A click on a comment focusses the map on the corresponding marker and opens the marker information.
This would also help spotting and deleting / correcting reported markers (since some people only report via comments, not via Discord).

**Comment by lmachens** [comment]
I will add a filter to display only markers with comments. I think this should solve the issue too :).
