### ISSUE TITLE
Suggestion: Harvest/Loot timer

### ISSUE THREAD

**Issue by cursxd** [lmachens/aeternum-map#65]
After harvesting or looting a resource/chest you can hit a hotkey and the nearest note or chest grays out and it shows the time above the note/chest till its respawn, the timer would be the max time it takes to respawn. Example:

Iron Vein Respawn Timer: 15 Mins
Supply Stockpile T5 Respawn Timer: 24 hours

**Comment by RyansGit** [comment]
Related to this suggestion... Add the option to display timers on the resource/chest before marking them as looted so you can work out it's reset timer before even looting it.

**Comment by lmachens** [comment]
Already implemented
