### ISSUE TITLE
Show a trace line of where you have been

### ISSUE THREAD

**Issue by RyansGit** [lmachens/aeternum-map#67]
Similar to the request for creating routes, have a "trace" route of where you've traveled.

- Allow me to define a time period of how long the line stays for, this is so it doesn't just become a mess of red lines on the map
- Provide a hotkey to clear the line progress on the map
- Ability to tie this in with the request #28 so that we can "save route"

**Comment by 360glitch** [comment]
This would be HUGE!

**Comment by Star4891** [comment]
Oh nice , i can't wait to see this 😃
