### ISSUE TITLE
Hotkey to toggle specific filters (sets of filters)

### ISSUE THREAD

**Issue by RyansGit** [lmachens/aeternum-map#68]
Add a hotkey to be able to enable/disable a number of map icon filters.

For example
- I would like a toggle to be able to turn on large chests and common chests
- I'd also like a hotkey to be able to enable ores/disable ores.

This is so I can have a tidy map for most of the time and temporarily enable certain filters.

Though #42 might also solve this issue, just not useful for people with 1 screen.

**Comment by josdemmers** [comment]
Although there are no hotkeys yet for this. We do have now presets to quickly switch between filters.
