### ISSUE TITLE
Ability to put a temporary marker on the map for direction

### ISSUE THREAD

**Issue by RyansGit** [lmachens/aeternum-map#69]
Add the ability to put a temporary marker on the map in the external map and then this would show in the minimap with a colored area on the side of the minimap to guide you to it, rather than doing it in-game.

Many of us have "farming routes" so one thing that would be nice would be to have a hotkey to add multiple markers on the map in an order and then have a hotkey to go to "next marker".

This could go hand in hand with #28 so that we can load up the next farming route.

**Comment by josdemmers** [comment]
The 'Generic' private marker could be used for this?

**Comment by lmachens** [comment]
I think so. Feel free to reopen.
