### ISSUE TITLE
Icon Shadows rather than Icons / Icon Bubbles

### ISSUE THREAD

**Issue by RyansGit** [lmachens/aeternum-map#82]
A change was made to this map which changed the icons from just the plain icon, to one with a circle around it and a coloured shaded background as you can see below.

![Before and After](https://i.imgur.com/E5tXbej.png)

This was to make the icons clearer on the map, however many found that the bubbles were too big and covered up too much and this for some people made it harder to read.

@lmachens updated the app so you can now choose what style you wanted, however in my opinion I believe it would actually look better with neither of these options.

The better option in my opinion would be to add shadows behind icons, allow users to choose the strength of the shadow behind the icons and how far out it "glows".

As for the color of these shadows, you could either go for a black shadow **OR** a colored shadow based on what resource they are, for example plants would appear with a green shadow.

Here is a mock up example of what I am talking about for the black shadows:

![Before and After](https://i.imgur.com/TeU48iR.png)

Here's another mspaint version of a thicker shadows **(Ignore how ugly the shadow looks, that's because I did it in paint!)**:

![Before and After](https://i.imgur.com/5w978to.png)

A happy medium I'd like to call this solution... It's more aggressive than the first solution, less aggressive than the second solution.

**Comment by lmachens** [comment]
Icon shadows were added. It's not so strong, like in the proposal, but should be fine.
If not, feel free to reopen.
