### ISSUE TITLE
Newly created "Cooking Ingredient" marker suddenly in wrong location

### ISSUE THREAD

**Issue by Sturmfunke** [lmachens/aeternum-map#84]
Location of marker: [8860.5, 4225.63, 6]
Name of marker: "Honey"

I've added this marker one day ago in a town (Everfall / Immerfall) where the honeystand is. I know that I put it in the right location, i was standing in front of the honeystand and the marker appeared correctly shortly after creating it. Now, while the marker is still in the town, it is at a different location. Something weird must have happened here.

Meanwhile, I've created another marker at the right location, again.

Edit: I will remove the marker if you can't find something strange on your end , and will keep an eye on that issue.

![image](https://user-images.githubusercontent.com/50137120/138230620-749ada6e-3d65-4c25-8d28-5841b5efb34c.png)

**Comment by lmachens** [comment]
I think it's related to #103. If this is still an issue, feel free to reopen.
